services:
  php:
    build:
      # context: ./docker/php
      # dockerfile: Dockerfile
      context: .                      # ðŸ‘ˆ raÃ­z del proyecto (no ./docker/php)
      dockerfile: ./docker/php/Dockerfile
    container_name: laravel_app_komercia
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      - TZ=America/Bogota
    depends_on:
      - db

  web:
    image: nginx:1.27-alpine
    container_name: nginx_komercia
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - node

  db:
    image: mysql:8.0
    container_name: mysql_komercia
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=komercia
      - MYSQL_USER=app
      - MYSQL_PASSWORD=app
      - MYSQL_ROOT_PASSWORD=root
      - TZ=America/Bogota
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - dbdata:/var/lib/mysql

  node:
    image: node:20
    container_name: node_komercia
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - node_modules:/var/www/node_modules   # volumen dedicado
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_HOST=0.0.0.0
      - NODE_OPTIONS=--max-old-space-size=4096
    ports:
      - "5173:5173"
    command: sh -lc "npm install && npm run dev -- --host 0.0.0.0"

  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit_komercia
    ports:
      - "8025:8025"   # UI web
      - "1025:1025"   # SMTP
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2
    container_name: phpmyadmin_komercia
    environment:
      - PMA_HOST=db          # nombre del servicio MySQL en tu compose
      - PMA_PORT=3306
      - PMA_ARBITRARY=1      # (opcional) permitir conectarse a otros hosts
      - UPLOAD_LIMIT=256M
      - MEMORY_LIMIT=512M
    depends_on:
      - db
    ports:
      - "8080:80"            # http://localhost:8080
    restart: unless-stopped

volumes:
  dbdata: {}
  node_modules: {}